name: release
on:
  push:
    branches:
      - develop
jobs:
  merge-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge develop into master
        run: |
          git fetch
          git branch
          git log | tail -n 1
          git merge origin/develop
          git push
#  tag-master:
#    needs: merge-develop
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Tag master
#        run: |
#          chmod +x ./bumpTag.sh
#          ./bumpTag.sh
