name: release
on:
  push:
    branches:
      - develop
jobs:
  merge-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge develop into master
        run: git merge develop
  tag-master:
    needs: merge-develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tag master
        working-directory: ./scripts
        run: |
          chmod +x bumpTag.sh
          sh bumpTag.sh
