name: release
on:
  push:
    branches:
      - develop
jobs:
  merge-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge develop into master
        run: |
          git merge develop
          git push
  tag-master:
    needs: merge-develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tag master
        run: |
          chmod +x ./github/workflows/scriptsbumpTag.sh
          ./github/workflows/scriptsbumpTag.sh
