name: release
on:
  push:
    branches:
      - develop
jobs:
  merge-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge develop into master
        run: |
          git fetch
          git merge develop
  tag-master:
    needs: merge-develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tag master
        working-directory: scripts
        run: |
          lastTag=$(git tag -l | tail -n 1)
          version=${lastTag##*-}
          major=${version%.*}
          minor=${version#*.}
          nextMinor=$((minor+1))
          git tag "$major.$nextMinor"
